appId: com.yoratoni.nextron
productName: Nextron Boilerplate
copyright: Copyright © 2024 Yoratoni
directories:
  output: dist
  buildResources: resources

files:
  - from: .
    filter:
      - package.json
      - app

extraResources:
  - from: main
    to: resources/main
    filter:
      - compiler-backend.jar

publish: null
